version: '3.8'
services:
    db:
        container_name: db.muhit.me
        image: mysql
        restart: always
        env_file:
            - ./.docker/mysql/my.env
        volumes:
            - db:/var/lib/mysql
            
    phpmyadmin:
        container_name: phpmyadmin.muhit.me
        image: phpmyadmin/phpmyadmin
        restart: always
        depends_on:
            - db
        environment:
            PMA_HOST: db
            PMA_PORT: 3306
            PMA_ARBITRARY: 1
        ports:
            - 8081:80

    composer:
        container_name: composer.muhit.me
        image: composer
        command: composer update
        volumes:
            - bedrock:/app

    web:
        container_name: local.muhit.me
        image: iammuhit/wordpress-bedrock
        restart: always
        build:
            context: ./.docker/web/apache
            dockerfile: Dockerfile
        depends_on:
            - composer
            - db
        env_file:
            - ./.docker/web/apache/.wp-docker.env
        volumes:
            - bedrock:/var/www
        ports:
            - 80:80
        extra_hosts:
            - local.muhit.me:127.0.0.1

networks:
    backend:

volumes:
    bedrock:
    db: