version: '3.9' 

services: 
    web:
        container_name: muhit.me
        image: iammuhit/wordpress-bedrock
        restart: always
        build:
            context: ./.docker/web/apache
            dockerfile: Dockerfile
        depends_on:
            - db
        ports:
            - 80:80
        environment:
            DB_HOST: ${DB_HOST}
            DB_NAME: ${DB_NAME}
            DB_USER: ${DB_USER}
            DB_PASSWORD: ${DB_PASSWORD}

            WP_ENV: ${WP_ENV}
            WP_HOME: ${WP_HOME}
            WP_SITENAME: ${WP_SITENAME}
            WP_ADMIN_USERNAME: ${WP_ADMIN_USERNAME}
            WP_ADMIN_PASSWORD: ${WP_ADMIN_PASSWORD}
            WP_ADMIN_EMAIL: ${WP_ADMIN_EMAIL}

            WP_CLI_ALLOW_ROOT: true
        volumes:
            - .:/var/www
            - db:/var/www/data/db
            - client:/var/www/client

    db:
        container_name: db.muhit.me
        image: mysql
        restart: always
        environment:
            MYSQL_DATABASE: ${DB_NAME}
            MYSQL_USER: ${DB_USER}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
        volumes:
            - ./data/db:/var/lib/mysql

    phpmyadmin:
        container_name: phpmyadmin.muhit.me
        image: phpmyadmin/phpmyadmin
        restart: always
        depends_on:
            - db
        environment:
            PMA_HOST: db
            PMA_PORT: 3306
            PMA_ARBITRARY: 1
            UPLOAD_LIMIT: 1024M
        ports:
            - 8081:80

volumes:
    backend:
    client:
    db:
