<?php

// A helper function to lookup "env_FILE", "env", then fallback
if (!function_exists('getenv_docker')) {
	function getenv_docker($env, $default) {
		if ($fileEnv = getenv($env . '_FILE')) {
			return rtrim(file_get_contents($fileEnv), "\r\n");
		} else if (($val = getenv($env)) !== false) {
			return $val;
		} else {
			return $default;
		}
	}
}

$docker_envs = [
    'DB_NAME'       => getenv_docker('WORDPRESS_DB_NAME', 'wordpress'),
    'DB_USER'       => getenv_docker('WORDPRESS_DB_USER', 'admin'),
    'DB_PASSWORD'   => getenv_docker('WORDPRESS_DB_PASSWORD', 'password'),
    'DB_HOST'       => getenv_docker('WORDPRESS_DB_HOST', 'db.muhit.me'),
    'DB_PREFIX'     => getenv_docker('WORDPRESS_DB_PREFIX', 'wp_'),
];

// TO-DO: merge with .env file

/**
 * Do not edit this file. Edit the config files found in the config/ dir instead.
 * This file is required in the root directory so WordPress can find it.
 * WP is hardcoded to look in its own directory or one directory up for wp-config.php.
 */
require_once dirname(__DIR__) . '/vendor/autoload.php';
require_once dirname(__DIR__) . '/config/application.php';
require_once ABSPATH . 'wp-settings.php';
